/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrame;
//Libreria de animaciones

import Class.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import static java.util.Collections.list;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import java.util.List;
import java.util.TimerTask;
import javax.swing.DefaultListModel;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Randald Villegas
 */
public class VentanaEstadisticas extends javax.swing.JFrame {
    DefaultListModel<String> listModel = new DefaultListModel<>();
    DefaultListModel<String> listModel2 = new DefaultListModel<>();
    VentanaInicio F1;
    Torneo t;

    /**
     * Creates new form Login
     */
    public VentanaEstadisticas(VentanaInicio F1,Torneo t) {
        initComponents();
        this.F1=F1;
        this.t=t;
        
        
        
        Jugador ganador = buscarganador();
        usuarioActual.setText(ganador.getNombreUsuario());
        jLabelFotoUsuario.setIcon(ganador.getFotografia());
        torneoNombre.setText(t.getNombreTorneo());
        
        listModel.clear();//limpiamos el listmodel
        for (int i = 0; i < Metodos.getInstance().getListaJugadoresTorneo().size(); i++) {//para agregar los jugadores
            String aux = Metodos.getInstance().getListaJugadoresTorneo().get(i).getNombreUsuario();
            listModel.addElement(aux);
        }
        jListPlayers.setModel(listModel);   
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jLabelTerminarTurno = new javax.swing.JLabel();
        jButtonNewGame = new javax.swing.JButton();
        tipoPregunta = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListPlayers = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListEstadisticas = new javax.swing.JList<>();
        torneoNombre = new javax.swing.JLabel();
        jLabelFotoUsuario = new javax.swing.JLabel();
        fechaAdmi = new javax.swing.JLabel();
        horaAdmi = new javax.swing.JLabel();
        usuarioActual = new javax.swing.JLabel();
        jButtonMostrarEstadisticas = new javax.swing.JButton();
        jLabelStrat = new javax.swing.JLabel();
        jLabelTorneo = new javax.swing.JLabel();
        jButtonOff = new javax.swing.JButton();
        jButtonHome = new javax.swing.JButton();
        jLabelPaloVertical = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        botonMinimizar = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setMaximumSize(new java.awt.Dimension(1000, 500));
        background.setMinimumSize(new java.awt.Dimension(1000, 500));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTerminarTurno.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        jLabelTerminarTurno.setForeground(new java.awt.Color(111, 174, 2));
        jLabelTerminarTurno.setText("New Game");
        background.add(jLabelTerminarTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 90, -1));

        jButtonNewGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/aceptar1.png"))); // NOI18N
        jButtonNewGame.setBorder(null);
        jButtonNewGame.setBorderPainted(false);
        jButtonNewGame.setContentAreaFilled(false);
        jButtonNewGame.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonNewGame.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/aceptar2.png"))); // NOI18N
        jButtonNewGame.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/aceptar2.png"))); // NOI18N
        jButtonNewGame.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/aceptar2.png"))); // NOI18N
        jButtonNewGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNewGameMouseClicked(evt);
            }
        });
        jButtonNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewGameActionPerformed(evt);
            }
        });
        background.add(jButtonNewGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, -1, -1));

        tipoPregunta.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        tipoPregunta.setForeground(new java.awt.Color(111, 174, 2));
        background.add(tipoPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 200, 50));

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        jScrollPane1.setOpaque(false);

        jListPlayers.setBackground(new java.awt.Color(0, 0, 0));
        jListPlayers.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jListPlayers.setForeground(new java.awt.Color(111, 174, 2));
        jListPlayers.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jListPlayers);

        background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 180, 130));

        jScrollPane2.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        jScrollPane2.setOpaque(false);

        jListEstadisticas.setBackground(new java.awt.Color(0, 0, 0));
        jListEstadisticas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jListEstadisticas.setForeground(new java.awt.Color(111, 174, 2));
        jListEstadisticas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(jListEstadisticas);

        background.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 480, 130));

        torneoNombre.setFont(new java.awt.Font("Script MT Bold", 0, 20)); // NOI18N
        torneoNombre.setForeground(new java.awt.Color(111, 174, 2));
        background.add(torneoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 180, 30));
        background.add(jLabelFotoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 150, 140));

        fechaAdmi.setFont(new java.awt.Font("Script MT Bold", 1, 18)); // NOI18N
        fechaAdmi.setForeground(new java.awt.Color(111, 174, 2));
        fechaAdmi.setToolTipText("");
        background.add(fechaAdmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 140, 30));

        horaAdmi.setFont(new java.awt.Font("Script MT Bold", 1, 18)); // NOI18N
        horaAdmi.setForeground(new java.awt.Color(111, 174, 2));
        horaAdmi.setToolTipText("");
        background.add(horaAdmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 60, 140, 30));

        usuarioActual.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        usuarioActual.setForeground(new java.awt.Color(111, 174, 2));
        background.add(usuarioActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 150, 30));

        jButtonMostrarEstadisticas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/aceptar1.png"))); // NOI18N
        jButtonMostrarEstadisticas.setBorder(null);
        jButtonMostrarEstadisticas.setBorderPainted(false);
        jButtonMostrarEstadisticas.setContentAreaFilled(false);
        jButtonMostrarEstadisticas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMostrarEstadisticas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/aceptar2.png"))); // NOI18N
        jButtonMostrarEstadisticas.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/aceptar2.png"))); // NOI18N
        jButtonMostrarEstadisticas.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/aceptar2.png"))); // NOI18N
        jButtonMostrarEstadisticas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMostrarEstadisticasMouseClicked(evt);
            }
        });
        background.add(jButtonMostrarEstadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 60, -1));

        jLabelStrat.setFont(new java.awt.Font("Script MT Bold", 0, 20)); // NOI18N
        jLabelStrat.setForeground(new java.awt.Color(111, 174, 2));
        jLabelStrat.setText("Tournament's name:");
        background.add(jLabelStrat, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, -1, -1));

        jLabelTorneo.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        jLabelTorneo.setForeground(new java.awt.Color(111, 174, 2));
        jLabelTorneo.setText("View Stadistics");
        background.add(jLabelTorneo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 130, -1));

        jButtonOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/off1.png"))); // NOI18N
        jButtonOff.setBorder(null);
        jButtonOff.setBorderPainted(false);
        jButtonOff.setContentAreaFilled(false);
        jButtonOff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonOff.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/off2.png"))); // NOI18N
        jButtonOff.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/off2.png"))); // NOI18N
        jButtonOff.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/off2.png"))); // NOI18N
        jButtonOff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonOffMouseClicked(evt);
            }
        });
        background.add(jButtonOff, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 20, -1, -1));

        jButtonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/log1.png"))); // NOI18N
        jButtonHome.setBorder(null);
        jButtonHome.setBorderPainted(false);
        jButtonHome.setContentAreaFilled(false);
        jButtonHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonHome.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/log2.png"))); // NOI18N
        jButtonHome.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/log2.png"))); // NOI18N
        jButtonHome.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/log2.png"))); // NOI18N
        jButtonHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonHomeMouseClicked(evt);
            }
        });
        background.add(jButtonHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 50));

        jLabelPaloVertical.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/paloPublicVertical.png"))); // NOI18N
        background.add(jLabelPaloVertical, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, 500));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/paloPublic.png"))); // NOI18N
        background.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 418, 1000, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/paloPublic.png"))); // NOI18N
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 94, 1000, 10));

        botonMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Expand_Arrow_32px.png"))); // NOI18N
        botonMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonMinimizarMouseClicked(evt);
            }
        });
        background.add(botonMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, 40, 50));

        jLabel6.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(111, 174, 2));
        jLabel6.setText("WINNER");
        background.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 130, 30));

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Login3.png"))); // NOI18N
        background.add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        
    }//GEN-LAST:event_formWindowOpened


    private void botonMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMinimizarMouseClicked
        //Para minimizar la ventana
        this.setState(JFrame.VentanaEstadisticas.ICONIFIED);
    }//GEN-LAST:event_botonMinimizarMouseClicked

    private void jButtonHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHomeMouseClicked
        Metodos.getInstance().getListaJugadoresTorneo().clear();
        VentanaLogin lg = new VentanaLogin();
        lg.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButtonHomeMouseClicked

    private void jButtonOffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOffMouseClicked
        Metodos.getInstance().cerrar();
    }//GEN-LAST:event_jButtonOffMouseClicked
    
    private void jButtonNewGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNewGameMouseClicked
        // BOTON para iniciar nuevo juego
        F1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonNewGameMouseClicked

    private void jButtonNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewGameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNewGameActionPerformed

    private void jButtonMostrarEstadisticasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMostrarEstadisticasMouseClicked
        //metodo para imprimir las estadisticas
        String jugador=jListPlayers.getSelectedValue();
        Jugador j = Metodos.getInstance().buscarJugador(jugador);
        listModel2.clear();
        listModel2.addElement("Puntaje= "+j.getPuntos());
        listModel2.addElement("Monedas= "+ j.getMonedas());
        listModel2.addElement("Saltos de Preguntas= " +(j.getMonedas()/3));
        listModel2.addElement("Porcentaja de aciertos por categoria:");
        for (int i = 0; i < j.getPorcentajeAciertos().size(); i++) {
           Promedio p= j.getPorcentajeAciertos().get(i);
           listModel2.addElement(p.getCategoria()+ "=   aciertas: "+(p.getCorrectas()/(p.getIncorrectas()+p.getCorrectas()))*100 + "   Desaciertas: "+(p.getIncorrectas()/(p.getCorrectas()+p.getIncorrectas()))*100);
        }
        jListEstadisticas.setModel(listModel2);
   
    }//GEN-LAST:event_jButtonMostrarEstadisticasMouseClicked
    public Jugador buscarganador(){
        Jugador ganador = new Jugador();
        for (int i = 0; i < Metodos.getInstance().getListaJugadoresTorneo().size(); i++) {
            Jugador aux = Metodos.getInstance().getListaJugadoresTorneo().get(i);
            if(aux.getPuntos()>=ganador.getPuntos()){
                ganador = aux;
            }
        }
        return ganador;
    }
    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Windows (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new VentanaEstadisticas(new VentanaInicio(""),new Torneo()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel botonMinimizar;
    private javax.swing.JLabel fechaAdmi;
    private javax.swing.JLabel horaAdmi;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonMostrarEstadisticas;
    private javax.swing.JButton jButtonNewGame;
    private javax.swing.JButton jButtonOff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelFotoUsuario;
    private javax.swing.JLabel jLabelPaloVertical;
    private javax.swing.JLabel jLabelStrat;
    private javax.swing.JLabel jLabelTerminarTurno;
    private javax.swing.JLabel jLabelTorneo;
    private javax.swing.JList<String> jListEstadisticas;
    private javax.swing.JList<String> jListPlayers;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel tipoPregunta;
    private javax.swing.JLabel torneoNombre;
    private javax.swing.JLabel usuarioActual;
    // End of variables declaration//GEN-END:variables
}
