/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrame;
//Libreria de animaciones

import AppPackage.AnimationClass;
import Class.Jugador;
import Class.Metodos;
import Class.Torneo;
import Class.Usuario;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import java.util.Collections;
import javax.swing.DefaultListModel;

/**
 *
 * @author Randald Villegas
 */
public class VentanaInicio extends javax.swing.JFrame {
    DefaultListModel<String> listModel = new DefaultListModel<>();
    String nombreUsuario;
    char tipoCantidadPreguntas;
    String datosCantidadPreguntas = "";
    /**
     * Creates new form Login
     */
    public VentanaInicio(String nombreUsuarioLogueado) {
        initComponents();
        
        nombreUsuario = nombreUsuarioLogueado;
        Usuario aux = Metodos.getInstance().buscarUsuario(nombreUsuario);
        Jugador aux2 = new Jugador(aux.getNombreCompleto(),aux.getNombreUsuario(), aux.getCorreo(), aux.getContraseña(), aux.getPais(),aux.getSexo(), aux.getFotografia());
        jugador.setText(aux.getNombreUsuario());
        
        Metodos.getInstance().setUsuarioLogueado(aux);
        Metodos.getInstance().getListaJugadoresTorneo().add(aux2);
        //hace aparecer en el centro de la pantalla
        this.setLocationRelativeTo(null);
        //Damos el saludo al usuario logueado
        usuarioActual.setText(null);
        usuarioActual.setText(nombreUsuarioLogueado);
        showDate();
        showTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        background = new javax.swing.JPanel();
        jTextFieldCantidadPreguntas = new javax.swing.JTextField();
        fechaAdmi = new javax.swing.JLabel();
        horaAdmi = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldNombreTorneo = new javax.swing.JTextField();
        jComboBoxCantidad = new javax.swing.JComboBox<>();
        jButtonAddPlayer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListCategorias = new javax.swing.JList<>();
        usuarioActual = new javax.swing.JLabel();
        jugador = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButtonNextPlayer = new javax.swing.JButton();
        jButtonBackPlayer = new javax.swing.JButton();
        jButtonStartTournament = new javax.swing.JButton();
        jLabelStrat = new javax.swing.JLabel();
        jLabelPlayers = new javax.swing.JLabel();
        JlabelPlayersIcon = new javax.swing.JButton();
        JLabelParticipantes = new javax.swing.JLabel();
        jLabelLevel = new javax.swing.JLabel();
        jButtonAddDificult = new javax.swing.JButton();
        jButtonDeleteDificult = new javax.swing.JButton();
        JlabelPlayers = new javax.swing.JButton();
        JlabelLevelIcon = new javax.swing.JButton();
        jButtonOff = new javax.swing.JButton();
        jButtonHome = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabelPaloVertical = new javax.swing.JLabel();
        JButtonConfiguracion = new javax.swing.JButton();
        JButtonPerfil = new javax.swing.JButton();
        jLabelNivel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        botonMinimizar = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabelBackground = new javax.swing.JLabel();

        jLabel11.setText("jLabel11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setMaximumSize(new java.awt.Dimension(1000, 500));
        background.setMinimumSize(new java.awt.Dimension(1000, 500));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldCantidadPreguntas.setBackground(new java.awt.Color(33, 33, 33));
        jTextFieldCantidadPreguntas.setFont(new java.awt.Font("Script MT Bold", 0, 14)); // NOI18N
        jTextFieldCantidadPreguntas.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldCantidadPreguntas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCantidadPreguntasKeyTyped(evt);
            }
        });
        background.add(jTextFieldCantidadPreguntas, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 140, 70, 30));

        fechaAdmi.setFont(new java.awt.Font("Script MT Bold", 1, 18)); // NOI18N
        fechaAdmi.setForeground(new java.awt.Color(111, 174, 2));
        fechaAdmi.setToolTipText("");
        background.add(fechaAdmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 140, 30));

        horaAdmi.setFont(new java.awt.Font("Script MT Bold", 1, 18)); // NOI18N
        horaAdmi.setForeground(new java.awt.Color(111, 174, 2));
        horaAdmi.setToolTipText("");
        background.add(horaAdmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 60, 140, 30));

        jLabel13.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Players Selected:");
        background.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 240, 150, -1));

        jLabel14.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Number of questions");
        background.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 140, 180, -1));

        jLabel15.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Add Player");
        background.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 90, -1));

        jTextFieldNombreTorneo.setBackground(new java.awt.Color(33, 33, 33));
        jTextFieldNombreTorneo.setFont(new java.awt.Font("Script MT Bold", 0, 14)); // NOI18N
        jTextFieldNombreTorneo.setForeground(new java.awt.Color(255, 255, 255));
        background.add(jTextFieldNombreTorneo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 160, 30));

        jComboBoxCantidad.setBackground(new java.awt.Color(0, 0, 0));
        jComboBoxCantidad.setFont(new java.awt.Font("Script MT Bold", 1, 18)); // NOI18N
        jComboBoxCantidad.setForeground(new java.awt.Color(111, 174, 2));
        jComboBoxCantidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        jComboBoxCantidad.setBorder(null);
        jComboBoxCantidad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBoxCantidad.setOpaque(false);
        background.add(jComboBoxCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 60, -1));

        jButtonAddPlayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/adduser2.png"))); // NOI18N
        jButtonAddPlayer.setBorder(null);
        jButtonAddPlayer.setBorderPainted(false);
        jButtonAddPlayer.setContentAreaFilled(false);
        jButtonAddPlayer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAddPlayer.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/adduser1.png"))); // NOI18N
        jButtonAddPlayer.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/adduser1.png"))); // NOI18N
        jButtonAddPlayer.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/adduser1.png"))); // NOI18N
        jButtonAddPlayer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAddPlayerMouseClicked(evt);
            }
        });
        background.add(jButtonAddPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        jScrollPane1.setOpaque(false);

        jListCategorias.setBackground(new java.awt.Color(0, 0, 0));
        jListCategorias.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jListCategorias.setForeground(new java.awt.Color(111, 174, 2));
        jListCategorias.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jListCategorias);

        background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 270, 150, 130));

        usuarioActual.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        usuarioActual.setForeground(new java.awt.Color(111, 174, 2));
        background.add(usuarioActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 240, 30));

        jugador.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        jugador.setForeground(new java.awt.Color(255, 255, 255));
        jugador.setText("Name");
        background.add(jugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 150, -1));

        jLabel12.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Player:");
        background.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 70, -1));

        jButtonNextPlayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add1.png"))); // NOI18N
        jButtonNextPlayer.setBorder(null);
        jButtonNextPlayer.setBorderPainted(false);
        jButtonNextPlayer.setContentAreaFilled(false);
        jButtonNextPlayer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonNextPlayer.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add2.png"))); // NOI18N
        jButtonNextPlayer.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add2.png"))); // NOI18N
        jButtonNextPlayer.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add2.png"))); // NOI18N
        jButtonNextPlayer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNextPlayerMouseClicked(evt);
            }
        });
        background.add(jButtonNextPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, -1, -1));

        jButtonBackPlayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Minus1.png"))); // NOI18N
        jButtonBackPlayer.setBorder(null);
        jButtonBackPlayer.setBorderPainted(false);
        jButtonBackPlayer.setContentAreaFilled(false);
        jButtonBackPlayer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBackPlayer.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Minus2.png"))); // NOI18N
        jButtonBackPlayer.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Minus2.png"))); // NOI18N
        jButtonBackPlayer.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Minus2.png"))); // NOI18N
        jButtonBackPlayer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBackPlayerMouseClicked(evt);
            }
        });
        background.add(jButtonBackPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        jButtonStartTournament.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/aceptar1.png"))); // NOI18N
        jButtonStartTournament.setBorder(null);
        jButtonStartTournament.setBorderPainted(false);
        jButtonStartTournament.setContentAreaFilled(false);
        jButtonStartTournament.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonStartTournament.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/aceptar2.png"))); // NOI18N
        jButtonStartTournament.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/aceptar2.png"))); // NOI18N
        jButtonStartTournament.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/aceptar2.png"))); // NOI18N
        jButtonStartTournament.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonStartTournamentMouseClicked(evt);
            }
        });
        background.add(jButtonStartTournament, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, -1, -1));

        jLabelStrat.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        jLabelStrat.setForeground(new java.awt.Color(111, 174, 2));
        jLabelStrat.setText("Start Tournament");
        background.add(jLabelStrat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        jLabelPlayers.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        jLabelPlayers.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPlayers.setText("# Players");
        background.add(jLabelPlayers, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 100, -1));

        JlabelPlayersIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/partic1.png"))); // NOI18N
        JlabelPlayersIcon.setBorder(null);
        JlabelPlayersIcon.setBorderPainted(false);
        JlabelPlayersIcon.setContentAreaFilled(false);
        JlabelPlayersIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JlabelPlayersIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JlabelPlayersIconMouseClicked(evt);
            }
        });
        background.add(JlabelPlayersIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        JLabelParticipantes.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        JLabelParticipantes.setForeground(new java.awt.Color(255, 255, 255));
        JLabelParticipantes.setText("Select Players");
        background.add(JLabelParticipantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 110, 30));

        jLabelLevel.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        jLabelLevel.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLevel.setText("Level");
        background.add(jLabelLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jButtonAddDificult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add1.png"))); // NOI18N
        jButtonAddDificult.setBorder(null);
        jButtonAddDificult.setBorderPainted(false);
        jButtonAddDificult.setContentAreaFilled(false);
        jButtonAddDificult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAddDificult.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add2.png"))); // NOI18N
        jButtonAddDificult.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add2.png"))); // NOI18N
        jButtonAddDificult.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add2.png"))); // NOI18N
        jButtonAddDificult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAddDificultMouseClicked(evt);
            }
        });
        background.add(jButtonAddDificult, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        jButtonDeleteDificult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Minus1.png"))); // NOI18N
        jButtonDeleteDificult.setBorder(null);
        jButtonDeleteDificult.setBorderPainted(false);
        jButtonDeleteDificult.setContentAreaFilled(false);
        jButtonDeleteDificult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDeleteDificult.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Minus2.png"))); // NOI18N
        jButtonDeleteDificult.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Minus2.png"))); // NOI18N
        jButtonDeleteDificult.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Minus2.png"))); // NOI18N
        jButtonDeleteDificult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDeleteDificultMouseClicked(evt);
            }
        });
        background.add(jButtonDeleteDificult, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        JlabelPlayers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/soccer.png"))); // NOI18N
        JlabelPlayers.setBorder(null);
        JlabelPlayers.setBorderPainted(false);
        JlabelPlayers.setContentAreaFilled(false);
        JlabelPlayers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JlabelPlayers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JlabelPlayersMouseClicked(evt);
            }
        });
        background.add(JlabelPlayers, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));

        JlabelLevelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/copa1.png"))); // NOI18N
        JlabelLevelIcon.setBorder(null);
        JlabelLevelIcon.setBorderPainted(false);
        JlabelLevelIcon.setContentAreaFilled(false);
        JlabelLevelIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JlabelLevelIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JlabelLevelIconMouseClicked(evt);
            }
        });
        background.add(JlabelLevelIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        jButtonOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/off1.png"))); // NOI18N
        jButtonOff.setBorder(null);
        jButtonOff.setBorderPainted(false);
        jButtonOff.setContentAreaFilled(false);
        jButtonOff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonOff.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/off2.png"))); // NOI18N
        jButtonOff.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/off2.png"))); // NOI18N
        jButtonOff.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/off2.png"))); // NOI18N
        jButtonOff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonOffMouseClicked(evt);
            }
        });
        background.add(jButtonOff, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 20, -1, -1));

        jButtonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/log1.png"))); // NOI18N
        jButtonHome.setBorder(null);
        jButtonHome.setBorderPainted(false);
        jButtonHome.setContentAreaFilled(false);
        jButtonHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonHome.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/log2.png"))); // NOI18N
        jButtonHome.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/log2.png"))); // NOI18N
        jButtonHome.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/log2.png"))); // NOI18N
        jButtonHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonHomeMouseClicked(evt);
            }
        });
        background.add(jButtonHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/botonesperf-conf.png"))); // NOI18N
        background.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 210, 10, 60));

        jLabelPaloVertical.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/paloPublicVertical.png"))); // NOI18N
        background.add(jLabelPaloVertical, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, 500));

        JButtonConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/config-botton_on.png"))); // NOI18N
        JButtonConfiguracion.setBorder(null);
        JButtonConfiguracion.setBorderPainted(false);
        JButtonConfiguracion.setContentAreaFilled(false);
        JButtonConfiguracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JButtonConfiguracion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cofig-botton.png"))); // NOI18N
        JButtonConfiguracion.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cofig-botton.png"))); // NOI18N
        JButtonConfiguracion.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cofig-botton.png"))); // NOI18N
        JButtonConfiguracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JButtonConfiguracionMouseClicked(evt);
            }
        });
        background.add(JButtonConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 240, -1, -1));

        JButtonPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/perfil-botton_on.png"))); // NOI18N
        JButtonPerfil.setBorder(null);
        JButtonPerfil.setBorderPainted(false);
        JButtonPerfil.setContentAreaFilled(false);
        JButtonPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JButtonPerfil.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/perfil-botton.png"))); // NOI18N
        JButtonPerfil.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/perfil-botton.png"))); // NOI18N
        JButtonPerfil.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/perfil-botton.png"))); // NOI18N
        JButtonPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JButtonPerfilMouseClicked(evt);
            }
        });
        background.add(JButtonPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 200, -1, -1));

        jLabelNivel.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        jLabelNivel.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNivel.setText("1");
        background.add(jLabelNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 30, -1));

        jLabel10.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Level Selected:");
        background.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 120, -1));

        jLabel9.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tournament Name:");
        background.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 150, -1));

        jLabel5.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(111, 174, 2));
        jLabel5.setText("Welcome");
        background.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 80, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/paloPublic.png"))); // NOI18N
        background.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 418, 1000, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/paloPublic.png"))); // NOI18N
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 94, 1000, 10));

        botonMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Expand_Arrow_32px.png"))); // NOI18N
        botonMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonMinimizarMouseClicked(evt);
            }
        });
        background.add(botonMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, 40, 50));

        jButton1.setText("Consutas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        background.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 110, 40));

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Login3.png"))); // NOI18N
        jLabelBackground.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBackgroundMouseClicked(evt);
            }
        });
        background.add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        imprimirJugadoresSelecionados();

    }//GEN-LAST:event_formWindowOpened
    public void showDate() {
        //metodo que retorna la fecha
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        fechaAdmi.setText(s.format(d));
    }

    public void showTime() {
        //metodo que retorna la hora
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                horaAdmi.setText(s.format(d));
            }
        }).start();
    }

    private void botonMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMinimizarMouseClicked
        //Para minimizar la ventana
        this.setState(JFrame.VentanaInicio.ICONIFIED);
    }//GEN-LAST:event_botonMinimizarMouseClicked

    private void jButtonHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHomeMouseClicked
        Metodos.getInstance().getListaJugadoresTorneo().clear();
        VentanaLogin lg = new VentanaLogin();
        lg.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButtonHomeMouseClicked

    private void jButtonOffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOffMouseClicked
        Metodos.getInstance().cerrar();
    }//GEN-LAST:event_jButtonOffMouseClicked

    private void JlabelPlayersIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlabelPlayersIconMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JlabelPlayersIconMouseClicked

    private void JlabelLevelIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlabelLevelIconMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JlabelLevelIconMouseClicked

    private void jButtonAddDificultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddDificultMouseClicked
        //sube el nivel de la dificultad y se guarda en una variable en los metodos 
        int cantidad = Metodos.getInstance().getNivelSeleccionado();
        if (cantidad < 5) {
            cantidad++;
            Metodos.getInstance().setNivelSeleccionado(cantidad);
            jLabelNivel.setText(String.valueOf(cantidad));

        } else {
            JOptionPane.showMessageDialog(this, "You already selected the maximum level");
        }
    }//GEN-LAST:event_jButtonAddDificultMouseClicked

    private void jButtonDeleteDificultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDeleteDificultMouseClicked
        //baja el nivel de la dificultad y se guarda en una variable en los metodos 
        int cantidad = Metodos.getInstance().getNivelSeleccionado();
        if (cantidad > 1) {
            cantidad--;
            Metodos.getInstance().setNivelSeleccionado(cantidad);
            jLabelNivel.setText(String.valueOf(cantidad));

        } else {
            JOptionPane.showMessageDialog(this, "You already selected the minimum level!");
        }
    }//GEN-LAST:event_jButtonDeleteDificultMouseClicked

    private void jButtonStartTournamentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonStartTournamentMouseClicked
        // Creamos un nuevo torneo
        char cantidadPreguntasSeleccionadas = this.tipoCantidadPreguntas;
        if(!Character.isDigit(cantidadPreguntasSeleccionadas)){
            JOptionPane.showMessageDialog(null, "You must enter a number in the number of questions \n You selected:  " + datosCantidadPreguntas);
            jTextFieldCantidadPreguntas.setText("");
            datosCantidadPreguntas = "";
            return;
        }
        int tamanoLista = Metodos.getInstance().getListaJugadoresTorneo().size();
        if (jTextFieldNombreTorneo.getText().isEmpty() | jTextFieldCantidadPreguntas.getText().isEmpty() | tamanoLista < jComboBoxCantidad.getSelectedIndex()) {
            JOptionPane.showMessageDialog(rootPane, "Incorrect data");
            return;
        }
        int suma = (Metodos.getInstance().listaPreguntaSeleccionMultiples.size()) + (Metodos.getInstance().listaPreguntaSeleccionUnicas.size()) + (Metodos.getInstance().listaPreguntasVerdaderoFalso.size());
        if (Integer.parseInt(jTextFieldCantidadPreguntas.getText()) < 1) {
            JOptionPane.showMessageDialog(rootPane, "The Minimun number is 1");
            return;
        }
        if (Integer.parseInt(jTextFieldCantidadPreguntas.getText()) > suma) {
            JOptionPane.showMessageDialog(rootPane, "The Maximun number is :" + suma);
            return;
        } else {
            Metodos.getInstance().ordenarListaUsuarios();
            Torneo torneo = new Torneo(jTextFieldNombreTorneo.getText(), Metodos.getInstance().getListaJugadoresTorneo().size(), Integer.parseInt(jLabelNivel.getText()), Integer.parseInt(jTextFieldCantidadPreguntas.getText()),Metodos.getInstance().getListaJugadoresTorneo());
            Metodos.getInstance().listaTorneos.add(torneo);
            Metodos.getInstance().setTorneo(torneo);
            JOptionPane.showMessageDialog(rootPane, "Tournament add successful");
            VentanaTorneo vT = new VentanaTorneo(Metodos.getInstance().getListaJugadoresTorneo().get(0).getNombreUsuario(),this);
            vT.setVisible(true);
            this.setVisible(false);
        }
    

    }//GEN-LAST:event_jButtonStartTournamentMouseClicked

    private void JButtonPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JButtonPerfilMouseClicked
        VentanaEditarPerfil edit = new VentanaEditarPerfil(nombreUsuario);
        edit.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JButtonPerfilMouseClicked

    private void JButtonConfiguracionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JButtonConfiguracionMouseClicked

        //Para ir a la ventana de admin
        try {
            int dialoButton = JOptionPane.YES_NO_OPTION;
            int result = JOptionPane.showConfirmDialog(null, "his area is for system administrators, do you want to continue?", "Administrator profile", dialoButton);
            if (result == 0) {
                String admi = JOptionPane.showInputDialog("Full name");
                String contrasenaAdmi = JOptionPane.showInputDialog("Password");

                if (Metodos.getInstance().verificarAdmi(admi, contrasenaAdmi)) {
                    VentanaAdmi va = new VentanaAdmi(admi);
                    va.setVisible(true);
                    this.dispose();
                }

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_JButtonConfiguracionMouseClicked

    private void JlabelPlayersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlabelPlayersMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JlabelPlayersMouseClicked

    private void jButtonBackPlayerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBackPlayerMouseClicked
        //metodo para moverse entre los jugadores hacia la izquierda
        int aux = Metodos.getInstance().getUsuarioSelecionado();
        aux--;
        if (aux == 0) {
            String aux3 = Metodos.getInstance().getListaUsuarios().get(aux).getNombreUsuario();
            jugador.setText(aux3);
            JOptionPane.showMessageDialog(this, "This is the first player!");
        } else {
            Metodos.getInstance().setUsuarioSelecionado(aux);
            String aux2 = Metodos.getInstance().getListaUsuarios().get(aux).getNombreUsuario();
            jugador.setText(aux2);
        }
    }//GEN-LAST:event_jButtonBackPlayerMouseClicked

    private void jButtonNextPlayerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNextPlayerMouseClicked
        //metodo para moverse entre los jugadores hacia la derecha
        int aux = Metodos.getInstance().getUsuarioSelecionado();
        aux++;
        if (aux > Metodos.getInstance().getListaUsuarios().size() - 1) {
            JOptionPane.showMessageDialog(this, "This is the last player!");
        } else {

            String aux2 = Metodos.getInstance().getListaUsuarios().get(aux).getNombreUsuario();
            Metodos.getInstance().setUsuarioSelecionado(aux);
            jugador.setText(aux2);
        }
    }//GEN-LAST:event_jButtonNextPlayerMouseClicked

    private void jButtonAddPlayerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddPlayerMouseClicked
        //metodo para selecionar los contrincantes del juego
        int jugadores = Metodos.getInstance().getCantidadJugadores();
        //int cantidadJugadores = Integer.parseInt(jLabelNumeroJugadores.getText());
        int cantidadJugadores = jComboBoxCantidad.getSelectedIndex()+1;
        if (jugadores == cantidadJugadores){
            JOptionPane.showMessageDialog(rootPane, "You selected the maximun players");
        } else {
            boolean verifica = false;
            for (int i = 0; i < Metodos.getInstance().getListaJugadoresTorneo().size(); i++) {
                if (Metodos.getInstance().getListaJugadoresTorneo().get(i).getNombreUsuario().equals(jugador.getText())) {

                    verifica = true;
                }
            }
            if (verifica) {
                JOptionPane.showMessageDialog(rootPane, "This player is already selected");
            } else {
                Usuario aux = Metodos.getInstance().buscarUsuario(jugador.getText());
                Jugador aux2 = new Jugador(aux.getNombreCompleto(),aux.getNombreUsuario(), aux.getCorreo(), aux.getContraseña(), aux.getPais(),aux.getSexo(), aux.getFotografia());
                Metodos.getInstance().getListaJugadoresTorneo().add(aux2);
                jugadores++;
                Metodos.getInstance().setCantidadJugadores(jugadores);
            }
        }
        imprimirJugadoresSelecionados();

    }//GEN-LAST:event_jButtonAddPlayerMouseClicked

    private void jTextFieldCantidadPreguntasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCantidadPreguntasKeyTyped
        // Averiguar si es un int
        tipoCantidadPreguntas = evt.getKeyChar();
        datosCantidadPreguntas += tipoCantidadPreguntas;
        
    }//GEN-LAST:event_jTextFieldCantidadPreguntasKeyTyped

    private void jLabelBackgroundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBackgroundMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelBackgroundMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // BOTON PARA IR A CONSULTAS
        VentanaConsultas F1 = new VentanaConsultas(this);
        this.setVisible(false);
        F1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void imprimirJugadoresSelecionados(){
        //metodo para imprimir Juagdores Seleccionados 
        listModel.clear();//limpiamos el listmodel
        for (int i = 0; i < Metodos.getInstance().getListaJugadoresTorneo().size(); i++) {
            String aux = Metodos.getInstance().getListaJugadoresTorneo().get(i).getNombreUsuario();
            listModel.addElement(aux);
        }
        jListCategorias.setModel(listModel);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Windows (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicio("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonConfiguracion;
    private javax.swing.JButton JButtonPerfil;
    private javax.swing.JLabel JLabelParticipantes;
    private javax.swing.JButton JlabelLevelIcon;
    private javax.swing.JButton JlabelPlayers;
    private javax.swing.JButton JlabelPlayersIcon;
    private javax.swing.JPanel background;
    private javax.swing.JLabel botonMinimizar;
    private javax.swing.JLabel fechaAdmi;
    private javax.swing.JLabel horaAdmi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAddDificult;
    private javax.swing.JButton jButtonAddPlayer;
    private javax.swing.JButton jButtonBackPlayer;
    private javax.swing.JButton jButtonDeleteDificult;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonNextPlayer;
    private javax.swing.JButton jButtonOff;
    private javax.swing.JButton jButtonStartTournament;
    private javax.swing.JComboBox<String> jComboBoxCantidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelLevel;
    private javax.swing.JLabel jLabelNivel;
    private javax.swing.JLabel jLabelPaloVertical;
    private javax.swing.JLabel jLabelPlayers;
    private javax.swing.JLabel jLabelStrat;
    private javax.swing.JList<String> jListCategorias;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldCantidadPreguntas;
    private javax.swing.JTextField jTextFieldNombreTorneo;
    private javax.swing.JLabel jugador;
    private javax.swing.JLabel usuarioActual;
    // End of variables declaration//GEN-END:variables
}
