/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrame;
//Libreria de animaciones
import AppPackage.AnimationClass;
import Class.Categoria;
import Class.Metodos;
import Class.Pregunta;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
/**
 *
 * @author Randald Villegas
 */
public class VentanaAdmi extends javax.swing.JFrame {
    DefaultListModel<String> listModel = new DefaultListModel<>();
    DefaultListModel<String> listModel2 = new DefaultListModel<>();
    /**
     * Creates new form Login
     */
    public VentanaAdmi(String nombreUsuarioLogueado) {
        initComponents();
        
        //hace aparecer en el centro de la pantalla
        this.setLocationRelativeTo(null);
        //Damos el saludo al usuario logueado
        usuarioActual.setText(null);
        usuarioActual.setText(nombreUsuarioLogueado);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        descripcion1 = new javax.swing.JTextField();
        fecha1 = new javax.swing.JTextField();
        hora1 = new javax.swing.JTextField();
        botonAgregar1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListUsuarios1 = new javax.swing.JList<>();
        botonEventos2 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListEventos1 = new javax.swing.JList<>();
        botonEventos3 = new javax.swing.JButton();
        background = new javax.swing.JPanel();
        botonAgregar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListEventos = new javax.swing.JList<>();
        botonEventos = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        categoria = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListUsuarios2 = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListCategorias = new javax.swing.JList<>();
        botonEliminarCategoria = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        botonEventos1 = new javax.swing.JButton();
        usuarioActual = new javax.swing.JLabel();
        jLabelHome = new javax.swing.JLabel();
        jButtonOff = new javax.swing.JButton();
        jButtonHome = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        JButtonConfiguracion = new javax.swing.JButton();
        JButtonPerfil = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        botonMinimizar = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();
        jButtonHome2 = new javax.swing.JButton();

        jLabel11.setText("jLabel11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(51, 255, 0));
        jPanel5.setLayout(null);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel6.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Descripcion");
        jPanel6.add(jLabel9);
        jLabel9.setBounds(10, 70, 80, 15);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Fecha");
        jPanel6.add(jLabel10);
        jLabel10.setBounds(10, 40, 40, 15);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Hora");
        jPanel6.add(jLabel13);
        jLabel13.setBounds(10, 10, 40, 15);

        descripcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descripcion1ActionPerformed(evt);
            }
        });
        jPanel6.add(descripcion1);
        descripcion1.setBounds(10, 90, 210, 90);

        fecha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecha1ActionPerformed(evt);
            }
        });
        jPanel6.add(fecha1);
        fecha1.setBounds(80, 40, 140, 20);

        hora1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hora1ActionPerformed(evt);
            }
        });
        jPanel6.add(hora1);
        hora1.setBounds(80, 10, 140, 20);

        botonAgregar1.setBackground(new java.awt.Color(0, 0, 0));
        botonAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregar1ActionPerformed(evt);
            }
        });
        jPanel6.add(botonAgregar1);
        botonAgregar1.setBounds(90, 190, 50, 40);

        jPanel5.add(jPanel6);
        jPanel6.setBounds(10, 140, 230, 240);

        jListUsuarios1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jListUsuarios1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane3.setViewportView(jListUsuarios1);

        jPanel5.add(jScrollPane3);
        jScrollPane3.setBounds(10, 10, 230, 80);

        botonEventos2.setBackground(new java.awt.Color(0, 0, 0));
        botonEventos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEventos2ActionPerformed(evt);
            }
        });
        jPanel5.add(botonEventos2);
        botonEventos2.setBounds(100, 90, 50, 40);

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel7.setBackground(new java.awt.Color(51, 255, 0));
        jPanel7.setLayout(null);

        jListEventos1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jScrollPane4.setViewportView(jListEventos1);

        jPanel7.add(jScrollPane4);
        jScrollPane4.setBounds(10, 10, 230, 190);

        botonEventos3.setBackground(new java.awt.Color(0, 0, 0));
        botonEventos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEventos3ActionPerformed(evt);
            }
        });
        jPanel7.add(botonEventos3);
        botonEventos3.setBounds(100, 210, 50, 40);

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        background.setMaximumSize(new java.awt.Dimension(1000, 500));
        background.setMinimumSize(new java.awt.Dimension(1000, 500));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonAgregar.setBackground(new java.awt.Color(0, 0, 0));
        botonAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add4.png"))); // NOI18N
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });
        background.add(botonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 50, 40));

        jScrollPane2.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setOpaque(false);

        jListEventos.setBackground(new java.awt.Color(0, 0, 0));
        jListEventos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2), 3));
        jListEventos.setForeground(new java.awt.Color(255, 255, 255));
        jListEventos.setOpaque(false);
        jScrollPane2.setViewportView(jListEventos);

        background.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 420, 130));

        botonEventos.setBackground(new java.awt.Color(0, 0, 0));
        botonEventos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search.png"))); // NOI18N
        botonEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEventosActionPerformed(evt);
            }
        });
        background.add(botonEventos, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 50, 40));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel4.setOpaque(false);
        jPanel4.setLayout(null);

        categoria.setOpaque(false);
        categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriaActionPerformed(evt);
            }
        });
        jPanel4.add(categoria);
        categoria.setBounds(10, 10, 130, 40);

        background.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 150, 60));

        jListUsuarios2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jListUsuarios2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane5.setViewportView(jListUsuarios2);

        background.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, 150, 130));

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setOpaque(false);

        jListCategorias.setBackground(new java.awt.Color(0, 0, 0));
        jListCategorias.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jListCategorias.setForeground(new java.awt.Color(255, 255, 255));
        jListCategorias.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jListCategorias.setOpaque(false);
        jScrollPane1.setViewportView(jListCategorias);

        background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 150, 130));

        botonEliminarCategoria.setBackground(new java.awt.Color(0, 0, 0));
        botonEliminarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/delete2.png"))); // NOI18N
        botonEliminarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarCategoriaActionPerformed(evt);
            }
        });
        background.add(botonEliminarCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 50, 40));

        jLabel15.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(111, 174, 2));
        jLabel15.setText("Delete Category");
        background.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 130, -1));

        jLabel14.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(111, 174, 2));
        jLabel14.setText("Questions ");
        background.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 100, -1));

        jLabel12.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(111, 174, 2));
        jLabel12.setText("Add Categories");
        background.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 130, -1));

        jLabel6.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(111, 174, 2));
        jLabel6.setText("Categories");
        background.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 130, 120, -1));

        botonEventos1.setBackground(new java.awt.Color(0, 0, 0));
        botonEventos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/info.png"))); // NOI18N
        botonEventos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEventos1ActionPerformed(evt);
            }
        });
        background.add(botonEventos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 50, 40));

        usuarioActual.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        usuarioActual.setForeground(new java.awt.Color(111, 174, 2));
        background.add(usuarioActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 370, 30));

        jLabelHome.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        jLabelHome.setForeground(new java.awt.Color(111, 174, 2));
        jLabelHome.setText("Log Out");
        background.add(jLabelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 120, -1));

        jButtonOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/off1.png"))); // NOI18N
        jButtonOff.setBorder(null);
        jButtonOff.setBorderPainted(false);
        jButtonOff.setContentAreaFilled(false);
        jButtonOff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonOff.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/off2.png"))); // NOI18N
        jButtonOff.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/off2.png"))); // NOI18N
        jButtonOff.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/off2.png"))); // NOI18N
        jButtonOff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonOffMouseClicked(evt);
            }
        });
        background.add(jButtonOff, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 20, -1, -1));

        jButtonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/log1.png"))); // NOI18N
        jButtonHome.setBorder(null);
        jButtonHome.setBorderPainted(false);
        jButtonHome.setContentAreaFilled(false);
        jButtonHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonHome.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/log2.png"))); // NOI18N
        jButtonHome.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/log2.png"))); // NOI18N
        jButtonHome.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/log2.png"))); // NOI18N
        jButtonHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonHomeMouseClicked(evt);
            }
        });
        background.add(jButtonHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 50, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/botonesperf-conf.png"))); // NOI18N
        background.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 210, 50, 60));

        JButtonConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/config-botton_on.png"))); // NOI18N
        JButtonConfiguracion.setBorder(null);
        JButtonConfiguracion.setBorderPainted(false);
        JButtonConfiguracion.setContentAreaFilled(false);
        JButtonConfiguracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JButtonConfiguracion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cofig-botton.png"))); // NOI18N
        JButtonConfiguracion.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cofig-botton.png"))); // NOI18N
        JButtonConfiguracion.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cofig-botton.png"))); // NOI18N
        JButtonConfiguracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JButtonConfiguracionMouseClicked(evt);
            }
        });
        background.add(JButtonConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 240, -1, -1));

        JButtonPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/perfil-botton_on.png"))); // NOI18N
        JButtonPerfil.setBorder(null);
        JButtonPerfil.setBorderPainted(false);
        JButtonPerfil.setContentAreaFilled(false);
        JButtonPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JButtonPerfil.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/perfil-botton.png"))); // NOI18N
        JButtonPerfil.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/perfil-botton.png"))); // NOI18N
        JButtonPerfil.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/perfil-botton.png"))); // NOI18N
        JButtonPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JButtonPerfilMouseClicked(evt);
            }
        });
        background.add(JButtonPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(111, 174, 2));
        jLabel5.setText("Welcome");
        background.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 80, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/paloPublicVertical.png"))); // NOI18N
        background.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 10, 400));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/paloPublic.png"))); // NOI18N
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 94, 1000, 10));

        botonMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Expand_Arrow_32px.png"))); // NOI18N
        botonMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonMinimizarMouseClicked(evt);
            }
        });
        background.add(botonMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, 40, 50));

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Login3.png"))); // NOI18N
        background.add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        jButtonHome2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/hom.png"))); // NOI18N
        jButtonHome2.setBorder(null);
        jButtonHome2.setBorderPainted(false);
        jButtonHome2.setContentAreaFilled(false);
        jButtonHome2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonHome2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/hom2.png"))); // NOI18N
        jButtonHome2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/hom2.png"))); // NOI18N
        jButtonHome2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/hom2.png"))); // NOI18N
        jButtonHome2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonHome2MouseClicked(evt);
            }
        });
        background.add(jButtonHome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        
    }//GEN-LAST:event_formWindowOpened

    private void botonMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMinimizarMouseClicked
        //Para minimizar la ventana
        this.setState(JFrame.VentanaAdmi.ICONIFIED);
    }//GEN-LAST:event_botonMinimizarMouseClicked
    
    private void jButtonHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHomeMouseClicked
      
        VentanaLogin lg = new VentanaLogin();
        lg.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButtonHomeMouseClicked

    private void jButtonOffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOffMouseClicked
        cerrar();
    }//GEN-LAST:event_jButtonOffMouseClicked

    private void JButtonPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JButtonPerfilMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JButtonPerfilMouseClicked

    private void jButtonHome2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHome2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHome2MouseClicked

    private void JButtonConfiguracionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JButtonConfiguracionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JButtonConfiguracionMouseClicked

    private void botonEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEventosActionPerformed
        String categoria = jListCategorias.getSelectedValue();
        imprimirPreguntas(categoria);
        
    }//GEN-LAST:event_botonEventosActionPerformed
    public void imprimirPreguntas(String categoria){
        //metodo para imprimir preguuntas 
        listModel2.clear();//limpiamos el listmodel
        for (int i = 0; i < Metodos.getInstance().listaPreguntaSeleccionMultiples.size(); i++) {
            String aux = Metodos.getInstance().listaPreguntaSeleccionMultiples.get(i).getTipo();
            if(aux.equals(categoria)){
                Pregunta nuevo = Metodos.getInstance().listaPreguntaSeleccionMultiples.get(i);
                listModel2.addElement(nuevo.getPregunta());
                listModel2.addElement("^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^");
            }
        }
        for (int i = 0; i < Metodos.getInstance().listaPreguntaSeleccionUnicas.size(); i++) {
            String aux = Metodos.getInstance().listaPreguntaSeleccionUnicas.get(i).getTipo();
            if(aux.equals(categoria)){
                Pregunta nuevo = Metodos.getInstance().listaPreguntaSeleccionUnicas.get(i);
                listModel2.addElement(nuevo.getPregunta());
                listModel2.addElement("^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^");
            }
        }
        for (int i = 0; i < Metodos.getInstance().listaPreguntasVerdaderoFalso.size(); i++) {
            String aux = Metodos.getInstance().listaPreguntasVerdaderoFalso.get(i).getTipo();
            if(aux.equals(categoria)){
                Pregunta nuevo = Metodos.getInstance().listaPreguntasVerdaderoFalso.get(i);
                listModel2.addElement(nuevo.getPregunta());
                listModel2.addElement("^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^");
            }
        }
        jListEventos.setModel(listModel2);

    
    }
    private void categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoriaActionPerformed

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        int aux = Metodos.getInstance().getListaCategorias().size();
        if(categoria.getText().isEmpty() ){
            JOptionPane.showMessageDialog(rootPane, "Campo vacio \n "
               );
        }else{
            Categoria cat = new Categoria(categoria.getText(), Metodos.getInstance().aumentarCategoria());
            Metodos.getInstance().listaCategorias.add(cat);
            JOptionPane.showMessageDialog(rootPane, categoria.getText() + ":  Categoria agregada exitosamente");
        }

    }//GEN-LAST:event_botonAgregarActionPerformed

    private void botonEventos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEventos1ActionPerformed
        imprimirCategorias();
    }//GEN-LAST:event_botonEventos1ActionPerformed
    public void imprimirCategorias(){
        //metodo para imprimir Categorias 
        listModel.clear();//limpiamos el listmodel
        for (int i = 0; i < Metodos.getInstance().listaCategorias.size(); i++) {
            String aux = Metodos.getInstance().listaCategorias.get(i).getTipo();
            listModel.addElement(aux);
        }
        jListCategorias.setModel(listModel);
    }
    private void descripcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descripcion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descripcion1ActionPerformed

    private void fecha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecha1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fecha1ActionPerformed

    private void hora1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hora1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hora1ActionPerformed

    private void botonAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAgregar1ActionPerformed

    private void botonEventos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEventos2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEventos2ActionPerformed

    private void botonEventos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEventos3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEventos3ActionPerformed

    private void botonEliminarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarCategoriaActionPerformed
        String eliminar = jListCategorias.getSelectedValue();
        Metodos.getInstance().EliminarCategoria(eliminar);
        ////////////////falta aun terminar este metodo
        
    }//GEN-LAST:event_botonEliminarCategoriaActionPerformed
    public void cerrar(){
        //Para salir del sistema
        try {
            int dialoButton = JOptionPane.YES_NO_OPTION;
            int result = JOptionPane.showConfirmDialog(null, "Desea Salir del Sistema?", "EXIT", dialoButton);
            if (result == 0) {
                System.exit(0);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Windows (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAdmi("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonConfiguracion;
    private javax.swing.JButton JButtonPerfil;
    private javax.swing.JPanel background;
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonAgregar1;
    private javax.swing.JButton botonEliminarCategoria;
    private javax.swing.JButton botonEventos;
    private javax.swing.JButton botonEventos1;
    private javax.swing.JButton botonEventos2;
    private javax.swing.JButton botonEventos3;
    private javax.swing.JLabel botonMinimizar;
    private javax.swing.JTextField categoria;
    private javax.swing.JTextField descripcion1;
    private javax.swing.JTextField fecha1;
    private javax.swing.JTextField hora1;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonHome2;
    private javax.swing.JButton jButtonOff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelHome;
    private javax.swing.JList<String> jListCategorias;
    private javax.swing.JList<String> jListEventos;
    private javax.swing.JList<String> jListEventos1;
    private javax.swing.JList<String> jListUsuarios1;
    private javax.swing.JList<String> jListUsuarios2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel usuarioActual;
    // End of variables declaration//GEN-END:variables
}
