/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrame;
//Libreria de animaciones
import AppPackage.AnimationClass;
import Class.Metodos;
import javax.swing.JOptionPane;
/**
 *
 * @author Randald Villegas
 */
public class VentanaInicio extends javax.swing.JFrame {
   
    /**
     * Creates new form Login
     */
    public VentanaInicio(String nombreUsuarioLogueado) {
        initComponents();
        
        //hace aparecer en el centro de la pantalla
        this.setLocationRelativeTo(null);
        //Damos el saludo al usuario logueado
        usuarioActual.setText(null);
        usuarioActual.setText(nombreUsuarioLogueado);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        background = new javax.swing.JPanel();
        usuarioActual = new javax.swing.JLabel();
        jugador = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButtonNextPlayer = new javax.swing.JButton();
        jButtonBackPlayer = new javax.swing.JButton();
        jButtonStartTournament = new javax.swing.JButton();
        jLabelStrat = new javax.swing.JLabel();
        jLabelHome = new javax.swing.JLabel();
        jLabelPlayers = new javax.swing.JLabel();
        jButtonDeleteParticipants = new javax.swing.JButton();
        JlabelPlayersIcon = new javax.swing.JButton();
        JLabelParticipantes = new javax.swing.JLabel();
        jButtonAddParticipants = new javax.swing.JButton();
        jLabelLevel = new javax.swing.JLabel();
        jButtonAddDificult = new javax.swing.JButton();
        jButtonDeleteDificult = new javax.swing.JButton();
        JlabelPlayers = new javax.swing.JButton();
        JlabelLevelIcon = new javax.swing.JButton();
        jButtonOff = new javax.swing.JButton();
        jButtonHome = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabelPaloVertical = new javax.swing.JLabel();
        JButtonConfiguracion = new javax.swing.JButton();
        JButtonPerfil = new javax.swing.JButton();
        jLabelNumeroJugadores = new javax.swing.JLabel();
        jLabelNivel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        botonMinimizar = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();
        jButtonHome2 = new javax.swing.JButton();

        jLabel11.setText("jLabel11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setMaximumSize(new java.awt.Dimension(1000, 500));
        background.setMinimumSize(new java.awt.Dimension(1000, 500));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usuarioActual.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        usuarioActual.setForeground(new java.awt.Color(111, 174, 2));
        background.add(usuarioActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 120, 30));

        jugador.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        jugador.setForeground(new java.awt.Color(111, 174, 2));
        jugador.setText("Name");
        background.add(jugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, 150, -1));

        jLabel12.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(111, 174, 2));
        jLabel12.setText("Player:");
        background.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 90, -1));

        jButtonNextPlayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add1.png"))); // NOI18N
        jButtonNextPlayer.setBorder(null);
        jButtonNextPlayer.setBorderPainted(false);
        jButtonNextPlayer.setContentAreaFilled(false);
        jButtonNextPlayer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonNextPlayer.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add2.png"))); // NOI18N
        jButtonNextPlayer.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add2.png"))); // NOI18N
        jButtonNextPlayer.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add2.png"))); // NOI18N
        jButtonNextPlayer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNextPlayerMouseClicked(evt);
            }
        });
        background.add(jButtonNextPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, -1, -1));

        jButtonBackPlayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Minus1.png"))); // NOI18N
        jButtonBackPlayer.setBorder(null);
        jButtonBackPlayer.setBorderPainted(false);
        jButtonBackPlayer.setContentAreaFilled(false);
        jButtonBackPlayer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBackPlayer.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Minus2.png"))); // NOI18N
        jButtonBackPlayer.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Minus2.png"))); // NOI18N
        jButtonBackPlayer.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Minus2.png"))); // NOI18N
        jButtonBackPlayer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBackPlayerMouseClicked(evt);
            }
        });
        background.add(jButtonBackPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        jButtonStartTournament.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/aceptar1.png"))); // NOI18N
        jButtonStartTournament.setBorder(null);
        jButtonStartTournament.setBorderPainted(false);
        jButtonStartTournament.setContentAreaFilled(false);
        jButtonStartTournament.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonStartTournament.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/aceptar2.png"))); // NOI18N
        jButtonStartTournament.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/aceptar2.png"))); // NOI18N
        jButtonStartTournament.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/aceptar2.png"))); // NOI18N
        jButtonStartTournament.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonStartTournamentMouseClicked(evt);
            }
        });
        background.add(jButtonStartTournament, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, -1, -1));

        jLabelStrat.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        jLabelStrat.setForeground(new java.awt.Color(111, 174, 2));
        jLabelStrat.setText("Start Tournament");
        background.add(jLabelStrat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        jLabelHome.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        jLabelHome.setForeground(new java.awt.Color(111, 174, 2));
        jLabelHome.setText("Home");
        background.add(jLabelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabelPlayers.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        jLabelPlayers.setForeground(new java.awt.Color(111, 174, 2));
        jLabelPlayers.setText("# Players");
        background.add(jLabelPlayers, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 100, -1));

        jButtonDeleteParticipants.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Minus1.png"))); // NOI18N
        jButtonDeleteParticipants.setBorder(null);
        jButtonDeleteParticipants.setBorderPainted(false);
        jButtonDeleteParticipants.setContentAreaFilled(false);
        jButtonDeleteParticipants.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDeleteParticipants.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Minus2.png"))); // NOI18N
        jButtonDeleteParticipants.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Minus2.png"))); // NOI18N
        jButtonDeleteParticipants.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Minus2.png"))); // NOI18N
        jButtonDeleteParticipants.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDeleteParticipantsMouseClicked(evt);
            }
        });
        background.add(jButtonDeleteParticipants, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        JlabelPlayersIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/partic1.png"))); // NOI18N
        JlabelPlayersIcon.setBorder(null);
        JlabelPlayersIcon.setBorderPainted(false);
        JlabelPlayersIcon.setContentAreaFilled(false);
        JlabelPlayersIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JlabelPlayersIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JlabelPlayersIconMouseClicked(evt);
            }
        });
        background.add(JlabelPlayersIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));

        JLabelParticipantes.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        JLabelParticipantes.setForeground(new java.awt.Color(111, 174, 2));
        JLabelParticipantes.setText("Select Players");
        background.add(JLabelParticipantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 110, 30));

        jButtonAddParticipants.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add1.png"))); // NOI18N
        jButtonAddParticipants.setBorder(null);
        jButtonAddParticipants.setBorderPainted(false);
        jButtonAddParticipants.setContentAreaFilled(false);
        jButtonAddParticipants.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAddParticipants.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add2.png"))); // NOI18N
        jButtonAddParticipants.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add2.png"))); // NOI18N
        jButtonAddParticipants.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add2.png"))); // NOI18N
        jButtonAddParticipants.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAddParticipantsMouseClicked(evt);
            }
        });
        background.add(jButtonAddParticipants, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        jLabelLevel.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        jLabelLevel.setForeground(new java.awt.Color(111, 174, 2));
        jLabelLevel.setText("Level");
        background.add(jLabelLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jButtonAddDificult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add1.png"))); // NOI18N
        jButtonAddDificult.setBorder(null);
        jButtonAddDificult.setBorderPainted(false);
        jButtonAddDificult.setContentAreaFilled(false);
        jButtonAddDificult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAddDificult.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add2.png"))); // NOI18N
        jButtonAddDificult.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add2.png"))); // NOI18N
        jButtonAddDificult.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add2.png"))); // NOI18N
        jButtonAddDificult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAddDificultMouseClicked(evt);
            }
        });
        background.add(jButtonAddDificult, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        jButtonDeleteDificult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Minus1.png"))); // NOI18N
        jButtonDeleteDificult.setBorder(null);
        jButtonDeleteDificult.setBorderPainted(false);
        jButtonDeleteDificult.setContentAreaFilled(false);
        jButtonDeleteDificult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDeleteDificult.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Minus2.png"))); // NOI18N
        jButtonDeleteDificult.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Minus2.png"))); // NOI18N
        jButtonDeleteDificult.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Minus2.png"))); // NOI18N
        jButtonDeleteDificult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDeleteDificultMouseClicked(evt);
            }
        });
        background.add(jButtonDeleteDificult, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        JlabelPlayers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/soccer.png"))); // NOI18N
        JlabelPlayers.setBorder(null);
        JlabelPlayers.setBorderPainted(false);
        JlabelPlayers.setContentAreaFilled(false);
        JlabelPlayers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JlabelPlayers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JlabelPlayersMouseClicked(evt);
            }
        });
        background.add(JlabelPlayers, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));

        JlabelLevelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/copa1.png"))); // NOI18N
        JlabelLevelIcon.setBorder(null);
        JlabelLevelIcon.setBorderPainted(false);
        JlabelLevelIcon.setContentAreaFilled(false);
        JlabelLevelIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JlabelLevelIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JlabelLevelIconMouseClicked(evt);
            }
        });
        background.add(JlabelLevelIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        jButtonOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/off1.png"))); // NOI18N
        jButtonOff.setBorder(null);
        jButtonOff.setBorderPainted(false);
        jButtonOff.setContentAreaFilled(false);
        jButtonOff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonOff.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/off2.png"))); // NOI18N
        jButtonOff.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/off2.png"))); // NOI18N
        jButtonOff.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/off2.png"))); // NOI18N
        jButtonOff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonOffMouseClicked(evt);
            }
        });
        background.add(jButtonOff, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 20, -1, -1));

        jButtonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/log1.png"))); // NOI18N
        jButtonHome.setBorder(null);
        jButtonHome.setBorderPainted(false);
        jButtonHome.setContentAreaFilled(false);
        jButtonHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonHome.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/log2.png"))); // NOI18N
        jButtonHome.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/log2.png"))); // NOI18N
        jButtonHome.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/log2.png"))); // NOI18N
        jButtonHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonHomeMouseClicked(evt);
            }
        });
        background.add(jButtonHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 50, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/botonesperf-conf.png"))); // NOI18N
        background.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 210, 50, 60));

        jLabelPaloVertical.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/paloPublicVertical.png"))); // NOI18N
        background.add(jLabelPaloVertical, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, 500));

        JButtonConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/config-botton_on.png"))); // NOI18N
        JButtonConfiguracion.setBorder(null);
        JButtonConfiguracion.setBorderPainted(false);
        JButtonConfiguracion.setContentAreaFilled(false);
        JButtonConfiguracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JButtonConfiguracion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cofig-botton.png"))); // NOI18N
        JButtonConfiguracion.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cofig-botton.png"))); // NOI18N
        JButtonConfiguracion.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cofig-botton.png"))); // NOI18N
        JButtonConfiguracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JButtonConfiguracionMouseClicked(evt);
            }
        });
        background.add(JButtonConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 240, -1, -1));

        JButtonPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/perfil-botton_on.png"))); // NOI18N
        JButtonPerfil.setBorder(null);
        JButtonPerfil.setBorderPainted(false);
        JButtonPerfil.setContentAreaFilled(false);
        JButtonPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JButtonPerfil.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/perfil-botton.png"))); // NOI18N
        JButtonPerfil.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/perfil-botton.png"))); // NOI18N
        JButtonPerfil.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/perfil-botton.png"))); // NOI18N
        JButtonPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JButtonPerfilMouseClicked(evt);
            }
        });
        background.add(JButtonPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 200, -1, -1));

        jLabelNumeroJugadores.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        jLabelNumeroJugadores.setForeground(new java.awt.Color(111, 174, 2));
        jLabelNumeroJugadores.setText("0");
        background.add(jLabelNumeroJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 30, -1));

        jLabelNivel.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        jLabelNivel.setForeground(new java.awt.Color(111, 174, 2));
        jLabelNivel.setText("0");
        background.add(jLabelNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 30, -1));

        jLabel10.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(111, 174, 2));
        jLabel10.setText("Level Selected:");
        background.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 120, -1));

        jLabel9.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(111, 174, 2));
        jLabel9.setText("Number of Players:");
        background.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 150, -1));

        jLabel5.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(111, 174, 2));
        jLabel5.setText("Welcome");
        background.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 80, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/paloPublic.png"))); // NOI18N
        background.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 418, 1000, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/paloPublic.png"))); // NOI18N
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 94, 1000, 10));

        botonMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Expand_Arrow_32px.png"))); // NOI18N
        botonMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonMinimizarMouseClicked(evt);
            }
        });
        background.add(botonMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, 40, 50));

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Login3.png"))); // NOI18N
        background.add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        jButtonHome2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/hom.png"))); // NOI18N
        jButtonHome2.setBorder(null);
        jButtonHome2.setBorderPainted(false);
        jButtonHome2.setContentAreaFilled(false);
        jButtonHome2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonHome2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/hom2.png"))); // NOI18N
        jButtonHome2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/hom2.png"))); // NOI18N
        jButtonHome2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/hom2.png"))); // NOI18N
        jButtonHome2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonHome2MouseClicked(evt);
            }
        });
        background.add(jButtonHome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        
    }//GEN-LAST:event_formWindowOpened

    private void botonMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMinimizarMouseClicked
        //Para minimizar la ventana
        this.setState(JFrame.VentanaInicio.ICONIFIED);
    }//GEN-LAST:event_botonMinimizarMouseClicked
    
    private void jButtonHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHomeMouseClicked
      
        VentanaLogin lg = new VentanaLogin();
        lg.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButtonHomeMouseClicked

    private void jButtonOffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOffMouseClicked
        cerrar();
    }//GEN-LAST:event_jButtonOffMouseClicked

    private void JlabelPlayersIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlabelPlayersIconMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JlabelPlayersIconMouseClicked

    private void JlabelLevelIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlabelLevelIconMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JlabelLevelIconMouseClicked

    private void jButtonAddParticipantsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddParticipantsMouseClicked
        int cantidad = Metodos.getInstance().getCantidadJugadores();
        if (cantidad < 5) {
            cantidad++;
            Metodos.getInstance().setCantidadJugadores(cantidad);
            jLabelNumeroJugadores.setText(String.valueOf(cantidad));
            
        }else{
            JOptionPane.showMessageDialog(this, "You already selected the maximum number of players!");
        }    
    }//GEN-LAST:event_jButtonAddParticipantsMouseClicked

    private void jButtonAddDificultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddDificultMouseClicked
        int cantidad = Metodos.getInstance().getNivelSeleccionado();
        if (cantidad < 5) {
            cantidad++;
            Metodos.getInstance().setNivelSeleccionado(cantidad);
            jLabelNivel.setText(String.valueOf(cantidad));
            
        }else{
            JOptionPane.showMessageDialog(this, "You already selected the maximum level");
        }    
    }//GEN-LAST:event_jButtonAddDificultMouseClicked

    private void jButtonDeleteParticipantsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDeleteParticipantsMouseClicked
        int cantidad = Metodos.getInstance().getCantidadJugadores();
        if (cantidad > 1) {
            cantidad--;
            Metodos.getInstance().setCantidadJugadores(cantidad);
            jLabelNumeroJugadores.setText(String.valueOf(cantidad));
            
        }else{
            JOptionPane.showMessageDialog(this, "You already selected the minimum number of players!");
        }
    }//GEN-LAST:event_jButtonDeleteParticipantsMouseClicked

    private void jButtonDeleteDificultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDeleteDificultMouseClicked
        int cantidad = Metodos.getInstance().getNivelSeleccionado();
        if (cantidad > 1) {
            cantidad--;
            Metodos.getInstance().setNivelSeleccionado(cantidad);
            jLabelNivel.setText(String.valueOf(cantidad));
            
        }else{
            JOptionPane.showMessageDialog(this, "You already selected the minimum number of players!");
        }
    }//GEN-LAST:event_jButtonDeleteDificultMouseClicked

    private void jButtonStartTournamentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonStartTournamentMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonStartTournamentMouseClicked

    private void JButtonPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JButtonPerfilMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JButtonPerfilMouseClicked

    private void jButtonHome2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHome2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHome2MouseClicked

    private void JButtonConfiguracionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JButtonConfiguracionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JButtonConfiguracionMouseClicked

    private void JlabelPlayersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlabelPlayersMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JlabelPlayersMouseClicked

    private void jButtonBackPlayerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBackPlayerMouseClicked
        int aux = Metodos.getInstance().getUsuarioSelecionado();
        aux --;
        if (aux == 0){
            JOptionPane.showMessageDialog(this, "This is the first player!");
        }
        else {
            Metodos.getInstance().setUsuarioSelecionado(aux);
            String aux2 = Metodos.getInstance().getListaJugadores().get(aux).getJugador().getNombreUsuario();
            jugador.setText(aux2);
        }
    }//GEN-LAST:event_jButtonBackPlayerMouseClicked

    private void jButtonNextPlayerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNextPlayerMouseClicked
        int aux = Metodos.getInstance().getUsuarioSelecionado();
        aux++;
        if (aux > Metodos.getInstance().getListaJugadores().size()-1){
            JOptionPane.showMessageDialog(this, "This is the last player!");
        }
        else {
            
            String aux2 = Metodos.getInstance().getListaJugadores().get(aux).getJugador().getNombreUsuario();
            Metodos.getInstance().setUsuarioSelecionado(aux);
            jugador.setText(aux2);
       }
    }//GEN-LAST:event_jButtonNextPlayerMouseClicked
    public void cerrar(){
        //Para salir del sistema
        try {
            int dialoButton = JOptionPane.YES_NO_OPTION;
            int result = JOptionPane.showConfirmDialog(null, "Desea Salir del Sistema?", "EXIT", dialoButton);
            if (result == 0) {
                System.exit(0);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Windows (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicio("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonConfiguracion;
    private javax.swing.JButton JButtonPerfil;
    private javax.swing.JLabel JLabelParticipantes;
    private javax.swing.JButton JlabelLevelIcon;
    private javax.swing.JButton JlabelPlayers;
    private javax.swing.JButton JlabelPlayersIcon;
    private javax.swing.JPanel background;
    private javax.swing.JLabel botonMinimizar;
    private javax.swing.JButton jButtonAddDificult;
    private javax.swing.JButton jButtonAddParticipants;
    private javax.swing.JButton jButtonBackPlayer;
    private javax.swing.JButton jButtonDeleteDificult;
    private javax.swing.JButton jButtonDeleteParticipants;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonHome2;
    private javax.swing.JButton jButtonNextPlayer;
    private javax.swing.JButton jButtonOff;
    private javax.swing.JButton jButtonStartTournament;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelHome;
    private javax.swing.JLabel jLabelLevel;
    private javax.swing.JLabel jLabelNivel;
    private javax.swing.JLabel jLabelNumeroJugadores;
    private javax.swing.JLabel jLabelPaloVertical;
    private javax.swing.JLabel jLabelPlayers;
    private javax.swing.JLabel jLabelStrat;
    private javax.swing.JLabel jugador;
    private javax.swing.JLabel usuarioActual;
    // End of variables declaration//GEN-END:variables
}
